# Creates a deployment set 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart 
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/cart:4.0.0
        ports:
        - containerPort: 80 
--- 

apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  # type: LoadBalancer
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 80              # Port number of the service that it has to listen on 
      targetPort: 80        # Port number of the container that it has to forward to

---
# Ingress Resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  rules:
  - host: cart.robos-shop.online
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: cart-svc
            port:
              number: 80
  ingressClassName: nginx